### ISSUE TITLE
user readability issues

### ISSUE THREAD

**Issue by adamjonas** [learn-co-curriculum/activerecord-orms-tutorial#3] opened 2015-08-17 16:39 UTC
User: Artem Eremin
Batch: 000
Current Lesson: ActiveRecord ORM Tutorial

Location: https://learn.co/tracks/web-development-with-ruby-on-rails/object-relational-mappers-orms/activerecord-migrations-and-crud/activerecord-costume-store?track_id=5309&batch_id=76

Bug Description: A little bit of mess here. First you make a CreateCandies migration class, which creates :products table, and then you make CostumeStore model, and after that you create Candy instances.

**Comment by AnnJohn** [comment] 2015-08-19 18:43
Closing issue since it's a duplicate of one already raised.

**Closed by AnnJohn** 2015-08-19 18:43 UTC
